version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: cleanarch
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d:ro